import numpy as np
import matplotlib.pyplot as plt
from gaussian import set_seed,generate_gaussian
set_seed(1)
mu1=float(input("Enter mean for X1: "))
mu2=float(input("Enter mean for X2: "))
count=1000
sigma=1
X1=np.array(generate_gaussian(mu1,sigma,count))
X2=np.array(generate_gaussian(mu2,sigma,count))
print("\nX1 first 10 values:")
print(X1[:10])
print("\nX2 first 10 values:")
print(X2[:10])
X=np.column_stack((X1,X2))
mu=np.array([mu1,mu2])
print("\nMean vector:")
print(mu)
print("\nFirst 10 two dimensional values:")
print(X[:10])
covariance=np.cov(X,rowvar=False)
eigenvalues,eigenvectors=np.linalg.eig(covariance)
print("\nCovariance matrix:")
print(covariance)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)
x1=np.linspace(mu1-4,mu1+4,100)
x2=np.linspace(mu2-4,mu2+4,100)
X1_grid,X2_grid=np.meshgrid(x1,x2)
points=np.column_stack((X1_grid.ravel(),X2_grid.ravel()))
diff=points-mu
covariance_inv=np.linalg.inv(covariance)
value=np.sum((diff@covariance_inv)*diff,axis=1).reshape(X1_grid.shape)
plt.figure(figsize=(8,6))
plt.contour(X1_grid,X2_grid,value,levels=[1,2,3,4,5],linewidths=1.5)
plt.scatter(X[:,0],X[:,1],s=12,alpha=.45,label="Gaussian data")
plt.scatter(mu1,mu2,c="black",marker="x",s=120,linewidths=3,label="Mean")
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("1(d) Constant Density Curves")
plt.legend()
plt.grid(alpha=.25)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8,6))
plt.scatter(X[:,0],X[:,1],s=12,alpha=.45,label="Gaussian data")
plt.scatter(mu1,mu2,c="black",marker="x",s=120,linewidths=3,label="Mean")
for i in range(2):
    vector=eigenvectors[:,i]
    length=np.sqrt(eigenvalues[i])
    plt.quiver(mu1,mu2,vector[0]*length,vector[1]*length,angles="xy",scale_units="xy",scale=1,width=.006)
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("1(e) Eigenvectors and Major-Minor Axes")
plt.legend()
plt.grid(alpha=.25)
plt.axis("equal")
plt.tight_layout()
plt.show()
major=max(eigenvalues)
minor=min(eigenvalues)
print("\nMajor axis eigenvalue:")
print(major)
print("\nMinor axis eigenvalue:")
print(minor)
sigma11=2
sigma22=.5
C=np.array([[sigma11**2,0],[0,sigma22**2]])
C_sqrt=np.array([[sigma11,0],[0,sigma22]])
Y=mu+(X-mu)@C_sqrt
print("\nDiagonal covariance matrix:")
print(C)
print("\nFirst 10 values of Y:")
print(Y[:10])
covariance_Y=np.cov(Y,rowvar=False)
eigenvalues_Y,eigenvectors_Y=np.linalg.eig(covariance_Y)
print("\nCovariance matrix of Y:")
print(covariance_Y)
print("\nEigenvalues of Y:")
print(eigenvalues_Y)
print("\nEigenvectors of Y:")
print(eigenvectors_Y)
x1=np.linspace(mu1-6,mu1+6,100)
x2=np.linspace(mu2-2,mu2+2,100)
X1_grid,X2_grid=np.meshgrid(x1,x2)
points=np.column_stack((X1_grid.ravel(),X2_grid.ravel()))
diff=points-mu
covariance_inv=np.linalg.inv(covariance_Y)
value=np.sum((diff@covariance_inv)*diff,axis=1).reshape(X1_grid.shape)
plt.figure(figsize=(8,6))
plt.contour(X1_grid,X2_grid,value,levels=[1,2,3,4,5],linewidths=1.5)
plt.scatter(Y[:,0],Y[:,1],s=12,alpha=.45,label="Diagonal Gaussian")
plt.scatter(mu1,mu2,c="black",marker="x",s=120,linewidths=3,label="Mean")
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("2(c) Constant Density Curves - Diagonal Covariance")
plt.legend()
plt.grid(alpha=.25)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8,6))
plt.scatter(Y[:,0],Y[:,1],s=12,alpha=.45,label="Diagonal Gaussian")
plt.scatter(mu1,mu2,c="black",marker="x",s=120,linewidths=3,label="Mean")
for i in range(2):
    v=eigenvectors_Y[:,i]
    plt.plot([mu1-v[0]*2,mu1+v[0]*2],[mu2-v[1]*2,mu2+v[1]*2],linewidth=2)
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("2(d) Eigenvectors and Major-Minor Axes")
plt.legend()
plt.grid(alpha=.25)
plt.axis("equal")
plt.tight_layout()
plt.show()
major=max(eigenvalues_Y)
minor=min(eigenvalues_Y)
print("\nMajor axis eigenvalue:")
print(major)
print("\nMinor axis eigenvalue:")
print(minor)
sigma11=2
sigma22=1
sigma12=1
C=np.array([[sigma11**2,sigma12],[sigma12,sigma22**2]])
C_sqrt=np.linalg.cholesky(C)
Y3=mu+(X-mu)@C_sqrt.T
print("\nFull covariance matrix:")
print(C)
print("\nFirst 10 values of Y:")
print(Y3[:10])
x1=np.linspace(mu1-6,mu1+6,100)
x2=np.linspace(mu2-4,mu2+4,100)
X1_grid,X2_grid=np.meshgrid(x1,x2)
points=np.column_stack((X1_grid.ravel(),X2_grid.ravel()))
diff=points-mu
covariance_inv=np.linalg.inv(C)
value=np.sum((diff@covariance_inv)*diff,axis=1).reshape(X1_grid.shape)
plt.figure(figsize=(8,6))
plt.contour(X1_grid,X2_grid,value,levels=[1,2,3,4,5],linewidths=1.5)
plt.scatter(Y3[:,0],Y3[:,1],s=12,alpha=.45,label="Full Gaussian")
plt.scatter(mu1,mu2,c="black",marker="x",s=120,linewidths=3,label="Mean")
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("3(b) Constant Density Curves - Full Covariance")
plt.legend()
plt.grid(alpha=.25)
plt.tight_layout()
plt.show()
covariance_Y3=np.cov(Y3,rowvar=False)
eigenvalues_Y3,eigenvectors_Y3=np.linalg.eig(covariance_Y3)
print("\nCovariance matrix of Y:")
print(covariance_Y3)
print("\nEigenvalues:")
print(eigenvalues_Y3)
print("\nEigenvectors:")
print(eigenvectors_Y3)
mu_class1=np.array([2,5])
mu_class2=np.array([7,5])
C1=np.array([[4,1],[1,1]])
C2=np.array([[1,0],[0,4]])
L1=np.linalg.cholesky(C1)
L2=np.linalg.cholesky(C2)
Y1=mu_class1+(X-mu)@L1.T
Y2=mu_class2+(X-mu)@L2.T
print("\nClass 1 mean:")
print(mu_class1)
print("\nClass 2 mean:")
print(mu_class2)
print("\nFirst 10 values of Class 1:")
print(Y1[:10])
print("\nFirst 10 values of Class 2:")
print(Y2[:10])
plt.figure(figsize=(8,6))
plt.scatter(Y1[:,0],Y1[:,1],s=16,alpha=.45,label="Class 1")
plt.scatter(Y2[:,0],Y2[:,1],s=16,alpha=.45,label="Class 2")
plt.scatter(mu_class1[0],mu_class1[1],c="black",marker="x",s=140,linewidths=3,label="Class means")
plt.scatter(mu_class2[0],mu_class2[1],c="black",marker="x",s=140,linewidths=3)
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("4(b) Two Gaussian Classes")
plt.legend()
plt.grid(alpha=.25)
plt.tight_layout()
plt.show()
x1=np.linspace(-5,12,200)
x2=np.linspace(-2,13,200)
X1_grid,X2_grid=np.meshgrid(x1,x2)
points=np.column_stack((X1_grid.ravel(),X2_grid.ravel()))
inv_C1=np.linalg.inv(C1)
inv_C2=np.linalg.inv(C2)
d1=np.sum(((points-mu_class1)@inv_C1)*(points-mu_class1),axis=1)
d2=np.sum(((points-mu_class2)@inv_C2)*(points-mu_class2),axis=1)
boundary=(d1-d2).reshape(X1_grid.shape)
plt.figure(figsize=(8,6))
plt.scatter(Y1[:,0],Y1[:,1],s=16,alpha=.4,label="Class 1")
plt.scatter(Y2[:,0],Y2[:,1],s=16,alpha=.4,label="Class 2")
plt.contour(X1_grid,X2_grid,boundary,levels=[0],linewidths=2.5)
plt.scatter(mu_class1[0],mu_class1[1],c="black",marker="x",s=140,linewidths=3)
plt.scatter(mu_class2[0],mu_class2[1],c="black",marker="x",s=140,linewidths=3)
plt.xlabel("X1")
plt.ylabel("X2")
plt.title("4(c) Decision Boundary")
plt.legend()
plt.grid(alpha=.25)
plt.tight_layout()
plt.show()